### ISSUE TITLE
Some warnings when I build with ROS1 Noetic.

### ISSUE THREAD

**Issue by ghost** [ros-industrial/abb_experimental#132]
Hello, can you help me with these warnings? They are link to these packages : 
- abb_irb2400_moveit_plugins ;
- abb_irb120_support.

I show you warnings : 

- abb_irb2400_moveit_plugins  : 
![abb_irb2400_moveit_plugins](https://user-images.githubusercontent.com/66011580/146365342-2f418787-621b-43e0-be16-4f8c650baad8.png)

- abb_irb120_support  : 
![abb_irb120_support](https://user-images.githubusercontent.com/66011580/146365405-a5d62950-94d2-404a-b16b-d8917dd64d52.png)

Thanks a lot.

**Comment by gavanderhoorn** [comment]
First: please replace the screenshots with the actual text.

We've requested that in https://github.com/ros-industrial/industrial_core/issues/278 as well.

Having written that: these are all warnings, not errors.

Everything will still compile and function correctly.
