### ISSUE TITLE
irb120: collision material yellow should be rgba="1 1 0 1"

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/abb_experimental#17]

**Comment by gavanderhoorn** [comment]
Should it be? :)

**Comment by culletom** [comment]
I was surprised to hear this too! Just checked and urdfs in the abb repository are the same, so guess this will have to be changed across the board. Also, abb_orange and yellow are quite similar, so perhaps it could be changed to red?

**Comment by gavanderhoorn** [comment]
I'm not sure we actually have a standard colour for collision geometry.

**Comment by culletom** [comment]
Yea I imagine not considering its low importance. I'll just correct the rgba values in this repository and submit a PR

**Comment by gavanderhoorn** [comment]
Lets just wait for @Levi-Armstrong and see what the rationale is.

**Comment by Levi-Armstrong** [comment]
This is also an issue in the abb repository, but the rgba="0 1 1 1" is cyan so the name does not accurately describe the color. I don't have a preference on the color so either the name should be changed to cyan or the rgba should be updated. It is less work to update the rgba in the abb repository so this may be the best solution.

**Comment by gavanderhoorn** [comment]
If we are going to fix this, perhaps we should create a shared xacro that just defines all ABB colours. This can then be included in all ABB urdfs, making sure colours are consistent.

**Comment by shaun-edwards** [comment]
On the "shared xacro", make sure you namespace everything in such a way that it doesn't have naming collisions.  In the past I've found that multiple xacro definitions of something like `pi` have caused issues.  Unfortunately, I can't remember the "right" way.  I know....I'm no help :)

**Comment by gavanderhoorn** [comment]
This would be partially solved by #23 I think, @Levi-Armstrong?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn: You are correct, it does correct the rgb for the colour yellow. I believe the only open question is, if yellow is the appropriate colour for the collision geometry.

**Comment by gavanderhoorn** [comment]
I guess that is up to us. MoveIt will colour meshes reddish when they are in collision, iirc, so it would only be a visual aid for when inspecting the model or visualising state I guess. For (my) other pkgs, I've always just left collision and visual geometry material colour the same, but I can see the value of having separate colours.

I've no real preference.

**Comment by Levi-Armstrong** [comment]
If you have no preference I vote to leave it as is, the colour yellow.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: do you know why yellow was used for the ABB urdfs specifically?

**Comment by gavanderhoorn** [comment]
Afaict, all xacro macros now use `abb_resources` for the colours of the meshes (as far as they don't use Collada meshes).

Closing this as it's no longer an issue.
