### ISSUE TITLE
How can I connect ABB IRB120 on the RobotStudio 

### ISSUE THREAD

**Issue by james2254** [ros-industrial/abb_experimental#29]
After setting parameters，i run the server program，virtual FlexPendant report errors。How can solve this problem？I follow the steps in the ros wiki。The website is http://wiki.ros.org/abb/Tutorials。My robot is ABB IRB120。
![gk_v a2b7ij3 dmnpn xs r](https://cloud.githubusercontent.com/assets/15374283/12002852/87368df0-ab45-11e5-8020-5f2a5d6bd204.png)

**Comment by Levi-Armstrong** [comment]
@james2254: Were you able to resolve the issue; if not maybe I can help?

**Comment by james2254** [comment]
Thank you；I have solved this issue。@Levi-Armstrong

**Comment by gavanderhoorn** [comment]
@james2254: can this be closed?

**Comment by merium** [comment]
Hi 

How was this issue resolved?

**Comment by gavanderhoorn** [comment]
@merium: there shouldn't really be an issue: using either RobotStudio or real hw should work.

If you have a specific issue, could I ask you to open a new one?
