### ISSUE TITLE
Make indigo-devel branch the default branch

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb_experimental#31]
Mainly to avoid confusing users.

**Comment by Levi-Armstrong** [comment]
@shaun-edwards: It looks like I don't have the permissions to allow me to set the default branch, but it looks like it may have already been changed. Are you able to set the indigo-devel branch to the default if it has not already been done?

**Comment by shaun-edwards** [comment]
I believe this is fixed.  I've also updated your permissions @Levi-Armstrong.

**Comment by gavanderhoorn** [comment]
Thanks.
