### ISSUE TITLE
error : controller is taking too long to execute trajectory

### ISSUE THREAD

**Issue by xsmxsm** [ros-industrial/abb_experimental#37]
![kjxyw548lvr xen4 2o b 1](https://cloud.githubusercontent.com/assets/16012809/20124445/6fc5e086-a661-11e6-8de8-7ec551943974.jpg)
How can i solve it ?

**Comment by gavanderhoorn** [comment]
This is a duplicate of ros-industrial/abb#110.

@xsmxsm: could I please ask you to only open issues on one tracker? Cross-posting to both will not get your issue fixed any sooner.

Thanks.
