### ISSUE TITLE
Remaining Issues for IRB52

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/abb_experimental#55]
- [ ] Remove tabs in test launch files.
- [ ] Make use_gui parameter a private member of the joint_state_publisher node.
- [ ] Add readme.md. See [here](https://github.com/ros-industrial/abb/tree/kinetic-devel/abb_irb2400_support).
- [ ] Remove tabs from the xacro files.
- [ ] Change `xacro.py` -> `xacro`

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Did I miss anything in the list?

@marip8 Are you able the address the remaining issues for the irb52?

**Comment by gavanderhoorn** [comment]
This was all addressed by #60 and later PRs.
