### ISSUE TITLE
Typo in irb1600_6_12_macro.xacro file

### ISSUE THREAD

**Issue by keerthanamanivannan** [ros-industrial/abb_experimental#69]
In the particular line on the following link, the curly brackets for ${pi/2} isn't closed. 
@gavanderhoorn 

https://github.com/ros-industrial/abb_experimental/blob/kinetic-devel/abb_irb1600_support/urdf/irb1600_6_12_macro.xacro#L168

**Comment by gavanderhoorn** [comment]
Thanks for reporting this.

@AustinDeric actually submitted #50 which introduced this support package.

@keerthanamanivannan: would you be willing to fix this small problem and submit a PR for it?

**Comment by keerthanamanivannan** [comment]
sure!

**Comment by gavanderhoorn** [comment]
Fixed in #70.
