### ISSUE TITLE
all: incorrect maintainer email addresses

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb_experimental#83]
Many packages still list @shaun-edwards's old SwRI email in the `maintainer` tag.

This should either be updated to a current address, or the `maintainer` tag should be updated to reflect who is the current maintainer of these packages (@Levi-Armstrong?).

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: would you be ok with a PR changing all `maintainer` tags to your email address?

**Comment by Levi-Armstrong** [comment]
That works for me.

**Comment by gavanderhoorn** [comment]
Fixed in #86.
