### ISSUE TITLE
Support packages have run_depend/exec_depend on rviz

### ISSUE THREAD

**Issue by stwirth** [ros-industrial/abb_experimental#90]
We like to keep packages that are meant to be deployed on a robot with as few dependencies as possible. 
The *_support packages in this repository have run_depend/exec_depend dependencies on rviz:
https://github.com/ros-industrial/abb_experimental/blob/e5470cb3d564097576cc8e5b813c9a833bb3d75e/abb_irb1200_support/package.xml#L39-L45

Wouldn't it be "cleaner" to separate the robot description part from the robot visualization part?

**Comment by gavanderhoorn** [comment]
This seems to be a duplicate of https://github.com/ros-industrial/ros_industrial_issues/issues/50.

**Comment by stwirth** [comment]
Correct, thanks for the reference!
