### ISSUE TITLE
Inertial values for IRB 1200 models?

### ISSUE THREAD

**Issue by jonbinney** [ros-industrial/abb_experimental#97]
Looks like the 120 has inertial values defined in the URDF here: https://github.com/ros-industrial/abb_experimental/blob/e7e6c119c23ab257cb545450b927ed6df3920dcc/abb_irb120_support/urdf/irb120_3_58_macro.xacro

Does anyone know how those values were determined? @bhomberg and I are trying to determine those values for the IRB1200 5_90 and 7_70 models. We've contacted ABB and they aren't willing to share those values - did someone measure them?

/cc @stwirth

**Comment by shaun-edwards** [comment]
I don't know where they came from, but sometimes people use the CAD model to estimate them.  As you have found, the robot vendors do not provide this information.  I would use at your own risk.

**Comment by gavanderhoorn** [comment]
These were made up / guessed / approximated using SolidWorks (from ros-industrial/abb_experimental#18):

> The masses and inertial values for each link were calculated in solidworks. Adding the mass of each link gives a total of 18kg, which is lower than the robots actual value of 25kg. I contacted ABB about this, but the factory doesn't provide more accurate values for each link. They did say that solidworks values are accurate, but that they don't include the robot cable harness as the mass distribution is difficult to calculate. I updated the inertia tensors and cog origins to account for the new joint translations, but it might be worth double checking these values. The inertia tensor for link 6 seemed was causing problems in Gazebo (values were too small) so I ended up using a simplified matrix for this link.

See also https://github.com/ros-industrial/kuka_experimental/issues/128#issuecomment-383111315.

**Comment by gavanderhoorn** [comment]
I'm going to close this as it's not really an issue with the packages.

Feel free to keep commenting though.

**Comment by jonbinney** [comment]
Thanks for the info! We'll estimate the intertias as well as we can and submit a PR. They'll be useful for doing more realistic gazebo simulation of the robot.
